name: Terraform

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_dispatch:

env:
  TF_VERSION: "1.7.0"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup Google Cloud Credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: |
        export TF_VAR_google_credentials="$(cat credentials.json)"
        export TF_VAR_github_token="${{ secrets.GITHUB_TOKEN }}"
        terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        export TF_VAR_google_credentials="$(cat credentials.json)"
        export TF_VAR_github_token="${{ secrets.GITHUB_TOKEN }}"
        terraform plan -no-color
        continue-on-error: true